Repository kubesphere/ks-jenkins, pull requests merged in 2021-05, with the labels that each got.

#27 Add Prometheus plugin in formula.yaml
  formula.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#29 Add GitPod as an online tool
  .github/workflows/Dockerfile-ks-jenkins-cache
  .github/workflows/ks-jenkins-cache.yaml
  .gitpod.Dockerfile
  .gitpod.yml
  Makefile
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#31 Remove git pod cache images for docker hub
  .github/workflows/ks-jenkins-cache.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#32 Use the offical image of ks-jenkins-gitpod instead of the temporary one
  .gitpod.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS
