Repository kubesphere/ks-jenkins, pull requests merged in 2022-01, with the labels that each got.

#71 Bump kubernetes plugin from 1.27.5 to 1.31.2
  formula.yaml
Labels: size/XS, lgtm, approved, tide/merge-method-squash

#74 Fix the plugin dep errors
  Makefile
  formula.yaml
Labels: size/M, lgtm, approved

#77 Add pipeline-event plugin into formula.yaml
  formula.yaml
Labels: kind/feature, size/XS, lgtm

#79 Update docker images of official and experimental ks-jenkins
  README.md
Labels: documentation, size/XS, lgtm, approved
