Repository kubesphere/ks-jenkins, pull requests merged in 2023-03, with the labels that each got.

#78 Bump base Jenkins to 2.319.3
  formula.yaml
Labels: size/XS, lgtm, approved, tide/merge-method-squash

#96 upgrade subversion plugin
  .github/workflows/pull-request.yml
  Makefile
  README.md
  formula.yaml
Labels: size/S

#97 upgrade jenkins to 2.319.3
  Makefile
  README.md
  formula.yaml
Labels: size/XS, approved
